spring:
  kafka:
    bootstrap-servers: centos0:9092,centos1:9092,centos2:9092
    producer:
      acks: -1
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      transaction-id-prefix: transaction-id-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable:
          idempotence: true

    consumer:
      group-id: springboot-kafka
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      properties:
        isolation:
          level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer